import {
  BadgeDollarSign,
  Building2,
  Calendar,
  ClipboardList,
  FileSpreadsheet,
  Heart,
  Landmark,
  Ticket,
  Users,
  Wallet,
} from "lucide-react";
import { BOARD_MEMBERSHIP_ROLES } from "../../utils/memberBenefits";
import {
  buildAidsRows,
  buildBankChargesRows,
  buildBoardAllowancesRows,
  buildBoardMeetingsRows,
  buildBoardMembersRows,
  buildBookingsRows,
  buildEmployeesRows,
  buildEventsRows,
  buildIssuedChecksRows,
  buildMemberBenefitsRows,
  buildSettlementRows,
  buildTreasuryRows,
} from "./reportDataBuilders";
import { compareArabic, getTodayISO, sortByDateRefName } from "./reportUtils";

export const REPORT_MODULES = {
  treasury_ledger: {
    id: "treasury_ledger",
    title: "كشف الحركة المالية الشامل",
    subtitle: "سجل موحّد للحركات الواردة والمنصرفة من المصادر القديمة والجديدة",
    icon: Wallet,
    sources: ["transactions", "issued_checks"],
    dateField: "date",
    orientation: "landscape",
    sortLabel: "التاريخ تصاعديًا ثم المرجع ثم الجهة",
    searchPlaceholder: "ابحث بالتاريخ أو الجهة أو البيان أو المرجع...",
    emptyMessage: "لا توجد حركات مالية مطابقة للفلاتر الحالية.",
    fields: [
      { key: "date", label: "التاريخ" },
      { key: "typeLabel", label: "النوع" },
      { key: "reference", label: "المرجع" },
      { key: "party", label: "الجهة / المستفيد" },
      { key: "statement", label: "البيان" },
      { key: "income", label: "وارد", currency: true },
      { key: "expense", label: "منصرف", currency: true },
      { key: "statusLabel", label: "الحالة" },
    ],
    buildRows: buildTreasuryRows,
    sortRows: (rows) => sortByDateRefName(rows, "date", "reference", "party"),
  },
  issued_checks: {
    id: "issued_checks",
    title: "الشيكات الصادرة",
    subtitle: "يشمل الإعانات والسلف والرحلات والفاعليات وباقي الشيكات الإدارية",
    icon: FileSpreadsheet,
    sources: ["transactions", "issued_checks"],
    dateField: "date",
    orientation: "landscape",
    sortLabel: "التاريخ تصاعديًا ثم رقم الشيك ثم المستفيد",
    searchPlaceholder: "ابحث بالمستفيد أو رقم الشيك أو بند الصرف...",
    emptyMessage: "لا توجد شيكات صادرة مطابقة.",
    fields: [
      { key: "date", label: "التاريخ" },
      { key: "typeLabel", label: "نوع الشيك" },
      { key: "reference", label: "رقم الشيك" },
      { key: "party", label: "المستفيد" },
      { key: "purpose", label: "الغرض" },
      { key: "amount", label: "القيمة", currency: true },
      { key: "settlementLabel", label: "التسوية" },
      { key: "settlementStatusLabel", label: "الموقف" },
    ],
    buildRows: buildIssuedChecksRows,
    sortRows: (rows) => sortByDateRefName(rows, "date", "reference", "party"),
  },
  settlements: {
    id: "settlements",
    title: "أرشيف التسويات المعتمدة",
    subtitle: "يعرض الشيكات والسلف التي أغلقت بتسوية فعلية وفواتير معتمدة",
    icon: ClipboardList,
    sources: ["transactions", "issued_checks"],
    dateField: "approvalDate",
    orientation: "landscape",
    sortLabel: "تاريخ الاعتماد تصاعديًا ثم رقم الشيك ثم المسؤول",
    searchPlaceholder: "ابحث بالمسؤول أو رقم الشيك أو نوع التسوية...",
    emptyMessage: "لا توجد تسويات معتمدة مطابقة.",
    fields: [
      { key: "approvalDate", label: "تاريخ الاعتماد" },
      { key: "checkDate", label: "تاريخ الشيك" },
      { key: "typeLabel", label: "النوع" },
      { key: "reference", label: "رقم الشيك" },
      { key: "party", label: "المسؤول" },
      { key: "checkAmount", label: "القيمة", currency: true },
      { key: "spent", label: "المنصرف", currency: true },
      { key: "returned", label: "الرصيد", currency: true },
      { key: "invoicesCount", label: "الفواتير" },
      { key: "returnStatus", label: "الموقف" },
    ],
    buildRows: buildSettlementRows,
    sortRows: (rows) => sortByDateRefName(rows, "approvalDate", "reference", "party"),
  },
  bank_charges: {
    id: "bank_charges",
    title: "الخصومات والعمولات المباشرة",
    subtitle: "المصاريف البنكية التي تخصم من كشف الحساب دون إصدار شيك",
    icon: BadgeDollarSign,
    sources: ["transactions"],
    dateField: "date",
    orientation: "portrait",
    sortLabel: "التاريخ تصاعديًا ثم المرجع البنكي",
    searchPlaceholder: "ابحث بالتصنيف البنكي أو المرجع أو البيان...",
    emptyMessage: "لا توجد خصومات مباشرة مطابقة.",
    fields: [
      { key: "date", label: "التاريخ" },
      { key: "category", label: "التصنيف" },
      { key: "reference", label: "المرجع البنكي" },
      { key: "statement", label: "البيان" },
      { key: "amount", label: "القيمة", currency: true },
      { key: "statusLabel", label: "الحالة" },
    ],
    buildRows: buildBankChargesRows,
    sortRows: (rows) => sortByDateRefName(rows, "date", "reference", "category"),
  },
  aids: {
    id: "aids",
    title: "تقرير الإعانات",
    subtitle: "سجل الإعانات المصروفة للأعضاء مع نوع الإعانة والواقعة المرتبطة بها",
    icon: Heart,
    sources: ["transactions", "issued_checks"],
    dateField: "date",
    orientation: "landscape",
    sortLabel: "التاريخ تصاعديًا ثم العضو ثم رقم الشيك",
    searchPlaceholder: "ابحث باسم العضو أو نوع الإعانة أو رقم الشيك...",
    emptyMessage: "لا توجد إعانات مطابقة للفترة أو البحث.",
    fields: [
      { key: "date", label: "تاريخ الصرف" },
      { key: "memberName", label: "اسم العضو" },
      { key: "memberId", label: "الكود" },
      { key: "category", label: "نوع الإعانة" },
      { key: "relation", label: "صلة القرابة" },
      { key: "incidentDate", label: "تاريخ الواقعة" },
      { key: "reference", label: "رقم الشيك" },
      { key: "amount", label: "القيمة", currency: true },
    ],
    buildRows: buildAidsRows,
    sortRows: (rows) => sortByDateRefName(rows, "date", "reference", "memberName"),
  },
  employees: {
    id: "employees",
    title: "سجل الأعضاء",
    subtitle: "بيانات العضوية والخدمة والحالة النقابية في صورة تقرير إداري موحد",
    icon: Users,
    sources: ["employees"],
    dateField: "",
    orientation: "landscape",
    sortLabel: "الكود الوظيفي تصاعديًا ثم الاسم",
    searchPlaceholder: "ابحث بالكود أو الاسم أو الصفة أو جهة العمل...",
    emptyMessage: "لا توجد بيانات أعضاء مطابقة.",
    fields: [
      { key: "jobId", label: "الكود" },
      { key: "name", label: "الاسم" },
      { key: "membershipStatus", label: "الصفة" },
      { key: "memberState", label: "الحالة" },
      { key: "jobTitle", label: "المسمى الوظيفي" },
      { key: "workplace", label: "جهة العمل" },
      { key: "phone", label: "الموبايل" },
      { key: "subscriptionStatus", label: "الاشتراك" },
      { key: "retirementDate", label: "تاريخ المعاش" },
    ],
    buildRows: buildEmployeesRows,
    sortRows: (rows) => [...rows].sort((a, b) => compareArabic(a.jobId, b.jobId) || compareArabic(a.name, b.name)),
  },
  board_members: {
    id: "board_members",
    title: "تشكيل مجلس الإدارة",
    subtitle: "أعضاء المجلس الحاليين مرتبين إداريًا حسب الصفة ثم الاسم",
    icon: Building2,
    sources: ["employees"],
    dateField: "",
    orientation: "portrait",
    sortLabel: "الصفة الإدارية ثم الاسم",
    searchPlaceholder: "ابحث بالصفة أو الاسم أو جهة العمل...",
    emptyMessage: "لا توجد بيانات لأعضاء المجلس.",
    fields: [
      { key: "role", label: "الصفة" },
      { key: "name", label: "الاسم" },
      { key: "jobId", label: "الكود" },
      { key: "phone", label: "الموبايل" },
      { key: "specialization", label: "التخصص" },
      { key: "workplace", label: "جهة العمل" },
      { key: "memberState", label: "الحالة" },
    ],
    buildRows: buildBoardMembersRows,
    sortRows: (rows) =>
      [...rows].sort(
        (a, b) =>
          (BOARD_MEMBERSHIP_ROLES.indexOf(a.role) >= 0 ? BOARD_MEMBERSHIP_ROLES.indexOf(a.role) : BOARD_MEMBERSHIP_ROLES.length) -
            (BOARD_MEMBERSHIP_ROLES.indexOf(b.role) >= 0 ? BOARD_MEMBERSHIP_ROLES.indexOf(b.role) : BOARD_MEMBERSHIP_ROLES.length) ||
          compareArabic(a.name, b.name)
      ),
  },
  board_meetings: {
    id: "board_meetings",
    title: "سجل اجتماعات المجلس",
    subtitle: "محاضر الاجتماعات بعدد الحضور والقرارات والأعضاء المشاركين",
    icon: Landmark,
    sources: ["board_meetings", "employees"],
    dateField: "date",
    orientation: "landscape",
    sortLabel: "التاريخ تصاعديًا ثم عنوان الاجتماع",
    searchPlaceholder: "ابحث بعنوان الاجتماع أو أسماء الحضور...",
    emptyMessage: "لا توجد اجتماعات مجلس مطابقة.",
    fields: [
      { key: "date", label: "التاريخ" },
      { key: "title", label: "عنوان الاجتماع" },
      { key: "statusLabel", label: "الحالة" },
      { key: "attendeesCount", label: "الحضور" },
      { key: "decisionsCount", label: "القرارات" },
      { key: "attendeesNames", label: "الأعضاء الحاضرون" },
    ],
    buildRows: buildBoardMeetingsRows,
    sortRows: (rows) => sortByDateRefName(rows, "date", "title", "title"),
  },
  board_allowances: {
    id: "board_allowances",
    title: "بدلات مجلس الإدارة",
    subtitle: "مستخرج مجمع من التسويات المعتمدة لبدلات الجلسات والانتقال والضيافة",
    icon: BadgeDollarSign,
    sources: ["employees", "transactions", "issued_checks"],
    dateField: "lastAllowanceDate",
    orientation: "landscape",
    sortLabel: "الصفة الإدارية ثم الاسم",
    searchPlaceholder: "ابحث بالاسم أو الصفة أو تاريخ آخر بدل...",
    emptyMessage: "لا توجد بدلات مجلس معتمدة مطابقة.",
    fields: [
      { key: "role", label: "الصفة" },
      { key: "name", label: "الاسم" },
      { key: "lastAllowanceDate", label: "آخر اعتماد" },
      { key: "sessionsAllowance", label: "بدل جلسات", currency: true },
      { key: "travelAllowance", label: "بدل انتقال", currency: true },
      { key: "hospitalityAllowance", label: "بدل ضيافة", currency: true },
      { key: "totalAllowance", label: "الإجمالي", currency: true },
    ],
    buildRows: (sourceData) => buildBoardAllowancesRows(sourceData, BOARD_MEMBERSHIP_ROLES),
    sortRows: (rows) =>
      [...rows].sort(
        (a, b) =>
          (a.roleWeight ?? BOARD_MEMBERSHIP_ROLES.length) - (b.roleWeight ?? BOARD_MEMBERSHIP_ROLES.length) ||
          compareArabic(a.name, b.name)
      ),
  },
  events: {
    id: "events",
    title: "سجل الفعاليات والأنشطة",
    subtitle: "جدول الفعاليات بالسعة والحجز والتسعير والدعم المعتمد",
    icon: Calendar,
    sources: ["events"],
    dateField: "date",
    orientation: "landscape",
    sortLabel: "التاريخ تصاعديًا ثم اسم الفعالية",
    searchPlaceholder: "ابحث باسم الفعالية أو النوع أو المكان...",
    emptyMessage: "لا توجد فعاليات مطابقة.",
    fields: [
      { key: "date", label: "التاريخ" },
      { key: "title", label: "اسم الفعالية" },
      { key: "type", label: "النوع" },
      { key: "location", label: "المكان" },
      { key: "capacity", label: "السعة" },
      { key: "booked", label: "المحجوز" },
      { key: "available", label: "المتاح" },
      { key: "bookingWindow", label: "فترة الحجز" },
      { key: "pricing", label: "التسعير" },
      { key: "statusLabel", label: "الحالة" },
    ],
    buildRows: (sourceData) => buildEventsRows(sourceData, getTodayISO()),
    sortRows: (rows) => sortByDateRefName(rows, "date", "title", "title"),
  },
  bookings: {
    id: "bookings",
    title: "حجوزات الفعاليات",
    subtitle: "سجل الحجز والدفع والتكلفة والحالة لكل مشترك",
    icon: Ticket,
    sources: ["event_bookings", "events"],
    dateField: "eventDate",
    orientation: "landscape",
    sortLabel: "تاريخ الفعالية ثم اسم الفعالية ثم اسم العضو",
    searchPlaceholder: "ابحث بالفعالية أو اسم العضو أو الكود أو حالة الحجز...",
    emptyMessage: "لا توجد حجوزات مطابقة.",
    fields: [
      { key: "eventDate", label: "تاريخ الفعالية" },
      { key: "eventTitle", label: "الفعالية" },
      { key: "memberName", label: "العضو" },
      { key: "memberId", label: "الكود" },
      { key: "totalPax", label: "الأفراد" },
      { key: "totalCost", label: "التكلفة", currency: true },
      { key: "statusLabel", label: "الحالة" },
      { key: "paymentSummary", label: "الدفع" },
    ],
    buildRows: buildBookingsRows,
    sortRows: (rows) => sortByDateRefName(rows, "eventDate", "eventTitle", "memberName"),
  },
  member_benefits: {
    id: "member_benefits",
    title: "مزايا ودعم الأعضاء",
    subtitle: "كل ما تم تسجيله لصالح الأعضاء من دعم فعاليات ومزايا وجوائز وخدمات",
    icon: Heart,
    sources: ["member_benefits"],
    dateField: "date",
    orientation: "landscape",
    sortLabel: "التاريخ تصاعديًا ثم اسم العضو ثم نوع المزية",
    searchPlaceholder: "ابحث باسم العضو أو نوع المزية أو المرجع...",
    emptyMessage: "لا توجد مزايا أعضاء مطابقة.",
    fields: [
      { key: "date", label: "التاريخ" },
      { key: "memberName", label: "العضو" },
      { key: "memberId", label: "الكود" },
      { key: "benefitType", label: "نوع المزية" },
      { key: "eventTitle", label: "المرجع" },
      { key: "sourceLabel", label: "المصدر" },
      { key: "statusLabel", label: "الحالة" },
      { key: "amount", label: "القيمة", currency: true },
      { key: "notes", label: "الملاحظات" },
    ],
    buildRows: buildMemberBenefitsRows,
    sortRows: (rows) => sortByDateRefName(rows, "date", "benefitType", "memberName"),
  },
};

export const REPORT_GROUPS = [
  {
    id: "finance",
    label: "الماليات",
    moduleIds: ["treasury_ledger", "issued_checks", "settlements", "bank_charges", "aids"],
  },
  {
    id: "members",
    label: "شؤون الأعضاء",
    moduleIds: ["employees", "member_benefits"],
  },
  {
    id: "board",
    label: "مجلس الإدارة",
    moduleIds: ["board_members", "board_meetings", "board_allowances"],
  },
  {
    id: "activities",
    label: "الأنشطة والفاعليات",
    moduleIds: ["events", "bookings"],
  },
];
